### ISSUE TITLE
Error on sls deploy (Error: ENOTDIR: not a directory, scandir distutils-precedence.pth' serverless-wsgi)

### ISSUE THREAD

**Issue by eopeter** [logandk/serverless-wsgi#151]
I attempted: `sls wsgi serve` it works great and able to access flask api from curl.

When I attempt to deploy to AWS using `sls deploy`, I get the following error:

Error: ENOTDIR: not a directory, scandir distutils-precedence.pth' serverless-wsgi

Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Python executable not found for "runtime": python3.8
Serverless: Using default Python executable: python
Serverless: Packaging Python WSGI handler...
Serverless: Packaging required Python packages...
Serverless: Linking required Python packages...
platform-sdk fetching: GET https://api.serverless.com/core/meta
platform-sdk fetching: GET https://api.serverless.com/core/tenants/userName/applications/appName
platform-sdk fetching: GET https://api.serverless.com/core/meta
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Error --------------------------------------------------
 
  Error: ENOTDIR: not a directory, scandir '/Users/myuserName/Projects/TestProj/src/Services/MyService/distutils-precedence.pth'
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:123:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
  From previous event:
      at Package.resolveFilePathsAll (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:200:8)
      at Package.packageAll (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:124:17)
      at /usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:96:21
  From previous event:
      at Package.packageService (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:94:43)
  From previous event:
      at Object.package:createDeploymentArtifacts [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/package/package.js:58:71)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:518:17)
      at /usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:122:50
  From previous event:
      at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:102:22)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:498:55
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:533:24
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:533:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:168:33
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:155:74)
      at /usr/local/lib/node_modules/serverless/scripts/serverless.js:50:26
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/scripts/serverless.js:50:4)
      at Module._compile (internal/modules/cjs/loader.js:1138:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
      at Module.load (internal/modules/cjs/loader.js:986:32)
      at Function.Module._load (internal/modules/cjs/loader.js:879:14)
      at Module.require (internal/modules/cjs/loader.js:1026:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:47:1)
      at Module._compile (internal/modules/cjs/loader.js:1138:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
      at Module.load (internal/modules/cjs/loader.js:986:32)
      at Function.Module._load (internal/modules/cjs/loader.js:879:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.2
     Framework Version:         2.1.1
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.1.3
Python 3

**Comment by will-snavely** [comment]
Hi, I also ran into this problem. It seems related to some major churn that's happening in `setuptools`. To get my project to deploy, I had to specify an earlier version of `setuptools` in my `requirements.txt`; 47.3.2 worked for me (`setuptools==47.3.2` in `requirements.txt`).

I'm not sure what needs to be/can be done by the maintainers of this project to address this issue.

**Comment by logandk** [comment]
Based on your stacktrace, this is not coming from the wsgi plugin but serverless itself. Please raise the issue with serverless - closing for now

**Comment by mohammad-aqajani** [comment]
any following link for this issue on serverless repo?
