### ISSUE TITLE
Cannot set cookie with domain due to servername being unset in flask/wsgi

### ISSUE THREAD

**Issue by lukeplausin** [logandk/serverless-wsgi#155]
Hi,

I am trying to add a cookie to my WSGI lambda response with a domain entry. This is required because of cross-domain trust reasons...

When I try to set the cookie with a domain entry, werkzeug throws an exception because the servername is not set.

```
[ERROR]	2020-11-10T18:15:53.917Z	3512fe24-aff8-4df6-bcfc-4707d0f7455c	Exception on REDACTED [POST]
Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/task/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/task/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/task/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/task/flask_cognito.py", line 145, in decorator
    return fn(*args, **kwargs)
  File "REDACTED", line 98, in _transform_response
    secure=cookie['secure'], httponly=cookie['httponly']
  File "/var/task/werkzeug/wrappers/base_response.py", line 479, in set_cookie
    samesite=samesite,
  File "/var/task/werkzeug/http.py", line 1204, in dump_cookie
    domain = _make_cookie_domain(domain)
  File "/var/task/werkzeug/_internal.py", line 383, in _make_cookie_domain
    "Setting 'domain' for a cookie on a server running locally (ex: "
ValueError: Setting 'domain' for a cookie on a server running locally (ex: localhost) is not supported by complying browsers. You should have something like: '127.0.0.1 localhost dev.localhost' on your hosts file and then point your server to run on 'dev.localhost' and also set 'domain' for 'dev.localhost'
```

Would it be possible to set the wsgi servername using the request context?
FYI I am using AWS lambda with an ALB trigger, the event syntax is slightly different to the API gateway

**Comment by logandk** [comment]
Could you set up a minimal example (i.e. a flask app that sets a cross-domain cookie and exhibits this error)? Thanks
