### ISSUE TITLE
ServerlessError: Serverless command "wsgi" not found. 

### ISSUE THREAD

**Issue by a-nadig** [logandk/serverless-wsgi#168]
Hi,

When I try to use the `serverless wsgi serve` command to run my django server locally, I get the following error.
```
 % serverless wsgi serve
 Serverless Error ----------------------------------------
 
  ServerlessError: Serverless command "wsgi" not found. Did you mean "logs"? Run "serverless help" for a list of all available commands.
      at /snapshot/serverless/lib/classes/PluginManager.js:497:15
      at Array.reduce (<anonymous>)
      at PluginManager.getCommand (/snapshot/serverless/lib/classes/PluginManager.js:457:27)
      at PluginManager.validateCommand (/snapshot/serverless/lib/classes/PluginManager.js:587:10)
      at Serverless.run (/snapshot/serverless/lib/Serverless.js:237:24)
      at /snapshot/serverless/scripts/serverless.js:382:24

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.4.0
     Framework Version:         2.31.0 (standalone)
     Plugin Version:            4.5.2
     SDK Version:               4.2.2
     Components Version:        3.7.6
```
I have installed the latest version of `serverless-wsgi`  which is 1.7.6 as of writing this and I'm using MacOS BigSur 11.2.3

I'm a bit new to this and I'd really appreciate any advice on what I might be doing wrong. Thanks!

**Comment by a-nadig** [comment]
I was able to solve my issue. 
I reinstalled serverless from npm, reinstalled my plugins and verified they're installed as below.
`npm list | grep serverless-wsgi`
And also since my configuration file was not named `serverless.yml`, I made sure to specify the correct one in my `wsgi serve` command. Something like below:
```
sls wsgi serve -c serverless-aws.yml -p 8000
```
Hope this helps if anyone else stumbles upon this issue.
