### ISSUE TITLE
nodenamenr servname provided, or not known

### ISSUE THREAD

**Issue by andylockran** [logandk/serverless-wsgi#57]
I following the tutorial here: https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/: 
 
It was working wonderfully for me, but I've come back to it a few weeks later (all in git, so no changes) and I'm now getting the following error:
```
Traceback (most recent call last):
  File "/Users/aloughran/Code/node_modules/serverless-wsgi/serve.py", line 50, in <module>
    serve(*sys.argv[1:])
  File "/Users/aloughran/Code/node_modules/serverless-wsgi/serve.py", line 42, in serve
    use_evalex=True)
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known.
```

The problem is more than likely an issue with my configuration, but I'm lost on working out where the nodename/servname should be passed by the wsgi config, or what could be tripping me up.

Thanks in advance.

**Comment by andylockran** [comment]
Ok, weirdly `localhost` had been removed from my `/etc/hosts` file.

**Comment by prabhuSub** [comment]
@andylockran  - how did you solve it?
